[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "OomJan"
name = "BetterLethalVRM"
description = "VRM mod for Lethal Company"
websiteUrl = "https://github.com/OomJan/BetterLethalVRM"
containsNsfwContent = false

[package.dependencies]
# https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "README.md"
target = "README.md"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE.md"
target = "LICENSE.md"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/bundle.asset"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/bundle.asset"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/FastSpringBone10.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/FastSpringBone10.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/MToon.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/MToon.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/OomJan.BetterLethalVRM.deps.json"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/OomJan.BetterLethalVRM.deps.json"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/OomJan.BetterLethalVRM.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/OomJan.BetterLethalVRM.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/UniGLTF.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/UniGLTF.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/UniGLTF.Utils.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/UniGLTF.Utils.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/UniHumanoid.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/UniHumanoid.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/VRM10.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/VRM10.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/VrmLib.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/VrmLib.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/VRMShaders.GLTF.IO.Runtime.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/VRMShaders.GLTF.IO.Runtime.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/VRMShaders.GLTF.UniUnlit.Runtime.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/VRMShaders.GLTF.UniUnlit.Runtime.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/VRMShaders.VRM.IO.Runtime.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/VRMShaders.VRM.IO.Runtime.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/VRMShaders.VRM10.Format.Runtime.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/VRMShaders.VRM10.Format.Runtime.dll"

[[build.copy]]
source = "BetterLethalVRM/bin/Release/netstandard2.1/VRMShaders.VRM10.MToon10.Runtime.dll"
target = "BepInEx/plugins/OomJan-BetterLethalVRM/VRMShaders.VRM10.MToon10.Runtime.dll"

[publish]
communities = ["lethal-company"]

[publish.categories]
# The categories are available at https://thunderstore.io near of the search bar
lethal-company = ["bepinex", "mods"]
